<?php
/**
 * Get the plugin classmap
 *
 * @package Teydea_Studio\Hiring_Hub
 */

return [
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Universal_Modules\\Module_Endpoint_Settings' => '/deps/php/universal-modules/class-module-endpoint-settings.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Universal_Modules\\Module_Plugin_Row_Meta' => '/deps/php/universal-modules/class-module-plugin-row-meta.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Universal_Modules\\Module_Rewrite_Rules' => '/deps/php/universal-modules/class-module-rewrite-rules.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Universal_Modules\\Module_Settings_Page' => '/deps/php/universal-modules/class-module-settings-page.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Universal_Modules\\Module_Translations' => '/deps/php/universal-modules/class-module-translations.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Asset' => '/deps/php/utils/class-asset.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Cache' => '/deps/php/utils/class-cache.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Container' => '/deps/php/utils/class-container.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Environment' => '/deps/php/utils/class-environment.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\JSON' => '/deps/php/utils/class-json.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Module' => '/deps/php/utils/class-module.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Nonce' => '/deps/php/utils/class-nonce.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Plugin' => '/deps/php/utils/class-plugin.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Post' => '/deps/php/utils/class-post.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Post_Meta' => '/deps/php/utils/class-post-meta.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Screen' => '/deps/php/utils/class-screen.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Settings' => '/deps/php/utils/class-settings.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Strings' => '/deps/php/utils/class-strings.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Template' => '/deps/php/utils/class-template.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Type' => '/deps/php/utils/class-type.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\Uninstall' => '/deps/php/utils/class-uninstall.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Utils\\User' => '/deps/php/utils/class-user.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Closures' => '/deps/php/validatable-fields/class-closures.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Configuration' => '/deps/php/validatable-fields/class-configuration.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Dynamic_Fields_Group' => '/deps/php/validatable-fields/class-dynamic-fields-group.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Field' => '/deps/php/validatable-fields/class-field.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Field_Array_Of_Strings' => '/deps/php/validatable-fields/class-field-array-of-strings.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Field_Boolean' => '/deps/php/validatable-fields/class-field-boolean.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Field_Integer' => '/deps/php/validatable-fields/class-field-integer.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Field_String' => '/deps/php/validatable-fields/class-field-string.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Field_String_Of_Choice' => '/deps/php/validatable-fields/class-field-string-of-choice.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Fields_Group' => '/deps/php/validatable-fields/class-fields-group.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Key_Identifiable' => '/deps/php/validatable-fields/trait-key-identifiable.php',
	'Teydea_Studio\\Hiring_Hub\\Dependencies\\Validatable_Fields\\Validatable' => '/deps/php/validatable-fields/trait-validatable.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Apply_On_Link\\Block_Apply_On_Link' => '/src/extensions/apply-on-link/block-apply-on-link/class-block-apply-on-link.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Apply_On_Link\\Extension' => '/src/extensions/apply-on-link/class-extension.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Apply_On_Link\\Post_Meta' => '/src/extensions/apply-on-link/post-meta/class-post-meta.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Job_Specification\\Block_Job_Specification_Characteristics' => '/src/extensions/job-specification/block-job-specification-characteristics/class-block-job-specification-characteristics.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Job_Specification\\Block_Job_Specification_List' => '/src/extensions/job-specification/block-job-specification-list/class-block-job-specification-list.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Job_Specification\\Extension' => '/src/extensions/job-specification/class-extension.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Job_Specification\\Post_Meta' => '/src/extensions/job-specification/post-meta/class-post-meta.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Job_Specification\\Query_Loop_Filtering' => '/src/extensions/job-specification/query-loop-filtering/class-query-loop-filtering.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Job_Specification\\Settings_Page' => '/src/extensions/job-specification/settings-page/class-settings-page.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Query_Loop_Filtering\\Block_Query_Loop_Filtering_Button' => '/src/extensions/query-loop-filtering/block-query-loop-filtering-button/class-block-query-loop-filtering-button.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Query_Loop_Filtering\\Block_Query_Loop_Filtering_Container' => '/src/extensions/query-loop-filtering/block-query-loop-filtering-container/class-block-query-loop-filtering-container.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Query_Loop_Filtering\\Block_Query_Loop_Filtering_Filter' => '/src/extensions/query-loop-filtering/block-query-loop-filtering-filter/class-block-query-loop-filtering-filter.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Query_Loop_Filtering\\Block_Query_Loop_Filtering_Search_Field' => '/src/extensions/query-loop-filtering/block-query-loop-filtering-search-field/class-block-query-loop-filtering-search-field.php',
	'Teydea_Studio\\Hiring_Hub\\Extensions\\Query_Loop_Filtering\\Extension' => '/src/extensions/query-loop-filtering/class-extension.php',
	'Teydea_Studio\\Hiring_Hub\\Job' => '/src/class-job.php',
	'Teydea_Studio\\Hiring_Hub\\Modules\\Module_Block_Editor' => '/src/modules/class-module-block-editor.php',
	'Teydea_Studio\\Hiring_Hub\\Modules\\Module_Block_Patterns' => '/src/modules/block-patterns/class-module-block-patterns.php',
	'Teydea_Studio\\Hiring_Hub\\Modules\\Module_Extensions' => '/src/modules/class-module-extensions.php',
	'Teydea_Studio\\Hiring_Hub\\Modules\\Module_Post_Type' => '/src/modules/class-module-post-type.php',
	'Teydea_Studio\\Hiring_Hub\\Modules\\Module_Schema' => '/src/modules/schema/class-module-schema.php',
	'Teydea_Studio\\Hiring_Hub\\Modules\\Module_Settings_Page' => '/src/modules/settings-page/class-module-settings-page.php',
	'Teydea_Studio\\Hiring_Hub\\Modules\\Module_Templates' => '/src/modules/templates/class-module-templates.php',
	'Teydea_Studio\\Hiring_Hub\\Settings' => '/src/class-settings.php',
];
